# Generated by Django 6.1.1 on 2026-09-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(blank=True, choices=[('استفسار عن منتج', 'استفسار عن منتج'), ('التوصيل والتركيب', 'التوصيل والتركيب'), ('البيع لدينا', 'البيع لدينا'), ('ضمان وإرجاع', 'ضمان وإرجاع'), ('أمر آخر', 'أمر آخر')], max_length=60)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact message',
                'verbose_name_plural': 'Contact messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
