# Generated by Django 6.1.1 on 2026-10-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ar_description',
            field=models.TextField(blank=True, help_text='Short SEO text in Arabic for the category page'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Short SEO text in English for the category page'),
        ),
    ]
