# Generated by Django 6.1.1 on 2026-10-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_category_ar_description_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='kind',
            field=models.CharField(choices=[('message', 'Message'), ('order', 'Direct Order')], default='message', max_length=10),
        ),
    ]
