# Generated by Django 6.1.1 on 2026-09-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=300, verbose_name='Page')),
                ('visitor_key', models.CharField(db_index=True, max_length=40, verbose_name='Visitor')),
                ('referrer', models.CharField(blank=True, max_length=200, verbose_name='Referrer')),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=10, verbose_name='Device')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Visitor log',
                'verbose_name_plural': 'Visitor logs',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at', 'path'], name='dashboard_v_created_2e49e3_idx')],
            },
        ),
    ]
